### PR TITLE
Add extension from ndx-template

### PR DESCRIPTION
**Pull request by weiglszonja**
Extends `LabMetaData` with Pinto lab specific metadata.
See `README.md` for example usage, which should be updated once is https://github.com/catalystneuro/pinto-lab-to-nwb/pull/5 merged to be used from the interface.

### CODE REVIEW

**Comment by weiglszonja** [comment]
@CodyCBakerPhD prototype files are updated at [behavior/](https://s3.console.aws.amazon.com/s3/buckets/catalystneuro-processing?region=us-east-2&prefix=pinto-lab-to-nwb/behavior/&showversions=false)

**Comment by CodyCBakerPhD** [comment]
We should probably get this in to have a starting point for follow-ups, so I'm OK with merging this as is and fixing things as we go

One big thing I notice right away is the duplicate of the start time column on the trials table

image

**Comment by CodyCBakerPhD** [comment]
I'd also feel better if all the lowerCamelCase columns of the trials table, and maze/stim protocol tables, were changed to snake case but that might be a fair amount of work so IDK

**Review by CodyCBakerPhD — APPROVED** [review]

**Comment by weiglszonja** [comment]
> We should probably get this in to have a starting point for follow-ups, so I'm OK with merging this as is and fixing things as we go
> 
> One big thing I notice right away is the duplicate of the start time column on the trials table
> 
> image

For `start_time` I used the "StartOfTrial" timestamps from the "BehaviorTimes" struct, which is not the same as "startTime" from the "performance" struct, the clarification about these copied from the email from Renan:

Variables in the 'BehaviorTimes' structure
     'StartOfTrial'       Timestamp (seconds) of the first engine iteration belonging to a given trial (one more iteration than 'performance.startTime').
     'EndOfTrial'        Timestamp (seconds) of the last engine iteration belonging to a given trial.

Variables in the 'performance' structure
     'startTime'        Timestamp (seconds) of the engine iteration during which a given trial is initialized (one less iteration than 'BehaviorTimes.StartOfTrial').
     'trialTime'        Time elapsed (seconds) between the iteration when the trial was initialized (i.e., 'performance.startTime') and the last iteration in the trial.

**Pull request merged**
